Script started on 2018-01-27 17:28:17-0700
]0;casey@casey-VirtualBox: ~/Dropbox/cse122/FILEIO/lab11[01;32mcasey@casey-VirtualBox[00m:[01;34m~/Dropbox/cse122/FILEIO/lab11[00m$ make
gcc -g -Wall kml.c -c
gcc -g -Wall kml.o lab11.c
]0;casey@casey-VirtualBox: ~/Dropbox/cse122/FILEIO/lab11[01;32mcasey@casey-VirtualBox[00m:[01;34m~/Dropbox/cse122/FILEIO/lab11[00m$ valgrind ./a.out [A
==4375== Memcheck, a memory error detector
==4375== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==4375== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==4375== Command: ./a.out
==4375== 
==4375== Invalid write of size 1
==4375==    at 0x4C3304C: strncpy (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4375==    by 0x109BB4: main (lab11.c:125)
==4375==  Address 0x521c883 is 0 bytes after a block of size 3 alloc'd
==4375==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4375==    by 0x109741: main (lab11.c:47)
==4375== 
==4375== Invalid read of size 1
==4375==    at 0x4C32D04: strlen (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4375==    by 0x4E918C4: vfprintf (vfprintf.c:1643)
==4375==    by 0x4E98D63: fprintf (fprintf.c:32)
==4375==    by 0x109572: logfile (kml.c:197)
==4375==    by 0x109D23: main (lab11.c:135)
==4375==  Address 0x521c883 is 0 bytes after a block of size 3 alloc'd
==4375==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4375==    by 0x109741: main (lab11.c:47)
==4375== 
==4375== Invalid read of size 1
==4375==    at 0x4C32D04: strlen (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4375==    by 0x4E918C4: vfprintf (vfprintf.c:1643)
==4375==    by 0x4E98D63: fprintf (fprintf.c:32)
==4375==    by 0x109532: logfile (kml.c:195)
==4375==    by 0x109D23: main (lab11.c:135)
==4375==  Address 0x521c883 is 0 bytes after a block of size 3 alloc'd
==4375==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4375==    by 0x109741: main (lab11.c:47)
==4375== 
==4375== Invalid write of size 1
==4375==    at 0x4C3304C: strncpy (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4375==    by 0x109C4A: main (lab11.c:131)
==4375==  Address 0x521c922 is 0 bytes after a block of size 2 alloc'd
==4375==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4375==    by 0x1097A3: main (lab11.c:57)
==4375== 
==4375== 
==4375== HEAP SUMMARY:
==4375==     in use at exit: 0 bytes in 0 blocks
==4375==   total heap usage: 205 allocs, 205 frees, 81,422 bytes allocated
==4375== 
==4375== All heap blocks were freed -- no leaks are possible
==4375== 
==4375== For counts of detected and suppressed errors, rerun with: -v
==4375== ERROR SUMMARY: 52 errors from 4 contexts (suppressed: 0 from 0)
]0;casey@casey-VirtualBox: ~/Dropbox/cse122/FILEIO/lab11[01;32mcasey@casey-VirtualBox[00m:[01;34m~/Dropbox/cse122/FILEIO/lab11[00m$ exit
exit

Script done on 2018-01-27 17:28:35-0700
